### ISSUE TITLE
Can't pass in the offline component as a second parameter into RequiresConnection

### ISSUE THREAD

**Issue by dijimon** [rauchy/react-native-offline-mode#1]
I'm trying to implement offline mode for my app by using react-native-offline-mode component.

Here is my simple code:

index.ios.js

```
    import {
  AppRegistry
} from 'react-native'
import App from './src/app'
import OfflineMode from './src/offlineMode'
import RequiresConnection from 'react-native-offline-mode'

AppRegistry.registerComponent('App', () => RequiresConnection(App, OfflineMode));
```

app.js

```
import React, { Component } from 'react'
import {
  View,
  Text
} from 'react-native';

class App extends Component {
  render() {
    return (
      <View>
        <Text>online</Text>
      </View>
    );
  }
}

module.exports = App;
```

offlineMode.js

```
import React, { Component } from 'react'
import {
  View,
  Text
} from 'react-native';

class OfflineMode extends Component {
  render() {
    return (
      <View>
        <Text>offline</Text>
      </View>
    );
  }
}

module.exports = OfflineMode;
```

Documentation says that I can use custom component as a second parameter, but instead I get an error: "Cannot call a class as a function"

Any idea?
Thanks in advance.

**Comment by rauchy** [comment]
According to [this](https://github.com/rauchy/react-native-offline-mode/blob/master/index.js#L23), if the offline parameter is a function, it will be called, so you could change your `OfflineMode` component to a stateless component:

**Comment by rauchy** [comment]
According to [this](https://github.com/rauchy/react-native-offline-mode/blob/master/index.js#L23), if the offline parameter is a function, it will be called. So you could change your OfflineMode component to a stateless component:

```
import React, { Component } from 'react'
import {
  View,
  Text
} from 'react-native';

const OfflineMode = (() => {
  <View>
    <Text>offline</Text>
  </View>
});

module.exports = OfflineMode;
```

and it should do the trick. Let me know if you need an actual class, it should be a trivial change.

**Comment by dijimon** [comment]
It doesn't work as well.
Says: "RequiresConnection.render(): A valid React element (or null) must be returned"

**Comment by dijimon** [comment]
It would be better to use the same class as for the first parameter.
I mean:  RequiresConnection(onlineComponent, offlineComponent)

export class onlineComponent extends React.Component {
  ...
}

export class offlineComponent extends React.Component {
  ...
}

or to have some possibility to pass property to the onlineComponent
For example:  this.property.offline = true;  within the onlineComponent

**Comment by rauchy** [comment]
I think [this](https://github.com/rauchy/react-native-offline-mode/commit/46296ee941fd386a7c6f6b5655f7a9e60ed1d822) should do the trick. Let me know if it solves your problem.

**Comment by obromios** [comment]
This is a very useful component thank you, but it would be great to have a nice looking message screen that matches my app.  I am having the same trouble as dijimon. 

I had a look at 'this should do the trick' in the post above, but I regret I do not understand just what needs to be done, and I note that jijimon has not responded to it. Perhaps you could give a slightly longer explanation as to how to fix the problem.

**Comment by rauchy** [comment]
@obromios if you upgrade to 0.1.2  you should be able to pass down your own component class to the RequiresConnection function.

**Comment by obromios** [comment]
Thanks, I will give it a try over the next few days and let you know.

Chris

**Comment by obromios** [comment]
I just tried it and it worked perfectly! Thank you for your rapid response.

Chris

**Comment by rauchy** [comment]
Glad to help 👍
