### ISSUE TITLE
Is this library actively maintained?

### ISSUE THREAD

**Issue by marudy** [rauchy/react-native-offline-mode#11]
Hi @rauchy,

do you actively maintain this library?

I'm thinking to offer some additions but it seems there are PRs/issues not merged/resolved yet. Kindly let me know!

Thanks,
Tasos

**Comment by rauchy** [comment]
Hi, thanks for pinging. Sorry it took me so long!

I’m on paternity leave so any help with maintaining it for now will be appreciated. Care to help?

**Comment by marudy** [comment]
Hi @rauchy,

thanks for getting back and congrats for your child :-)

Yes I can help with the package maintenance. I am using a similar solution myself and was thinking to make it a package and then I saw you have implemented it already. Just didn't want to use and offer PRs to a package that is not maintained :)

You can also reach me in my email: tasos.maroudas@protonmail.com

**Comment by marudy** [comment]
Hey @rauchy,

if you would like me to help with the package, it's a good period for that. I have free days until I jumb to my next project :)

Thanks,
Tasos

**Comment by rauchy** [comment]
Perfect @marudy, appreciate the help!

Sorry for my delayed responses. The twins are starting preschool tomorrow and I shall transform back into my human form. Anyway, added you as collaborator 😄

**Comment by marudy** [comment]
Great mate!

Even better for me to work together! And as I have the free time now, I plan to work a bit on it :smile: and also add it to my upcoming projects!!

Ouuu twins hehe, all the best mate :)
