### ISSUE TITLE
 Error validating module options: child "platform" fails because ["platform" must be a string]

### ISSUE THREAD

**Issue by ahmed1490** [rauchy/react-native-offline-mode#2]
When i enable the plugin to my root of my react tree. the no internet popup comes up even if i have internet. and on the console i see

<img width="937" alt="screenshot" src="https://cloud.githubusercontent.com/assets/623510/16859564/28f70c76-4a30-11e6-81a4-3c6dacda568e.png">

**Comment by rauchy** [comment]
I'm not sure this is related to react-native-offline-mode. Have you searched around for related issues (perhaps https://github.com/facebook/react-native/issues/2645 ?)

If you still believe this is related to react-native-offline-mode, please provide some more details on how to reproduce this.

**Comment by rauchy** [comment]
Haven't heard back so I'm closing this for now. Feel free to re-open.
